### ISSUE TITLE
[FR] get EventID details

### ISSUE THREAD

**Issue by wuast94** [Skylar-Tech/node-red-contrib-matrix-chat#125] opened 2024-10-16 06:40 UTC
Becouse i played around a bit with reactions and how to get the message from a reacted message i just wanted to leave my code here and hope it helps. would be nice to have a node that returns informations about an eventID

```js
let matrixClient = global.get("matrixClient['@user:domain.tld']"),
    matrixOnline = global.get("matrixClientOnline['@user:domain.tld']");

if (!matrixOnline) {
    msg.error = 'Matrix client not connected.';
    return [null, msg];
}

const roomId = msg.roomId;
const eventId = msg.eventId;
const room = matrixClient.getRoom(roomId);

if (room) {
    const event = room.findEventById(eventId);
    if (event) {
        msg.eventDetails = {
            eventId: event.getId(),
            sender: event.getSender(),
            type: event.getType(),
            content: event.getContent(),
            timestamp: event.getTs()
        };
        node.send([msg, null]);
    } else {
        msg.error = 'Event not found.';
        node.send([null, msg]);
    }
} else {
    msg.error = 'Room not found.';
    node.send([null, msg]);
}
````

**Comment by skylord123** [comment] 2024-10-16 20:01
Next release will have a new `Get Event` node described here:
https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/issues/117

Also I added another node for the next release called `Fetch Event Relations` that let you paginate all events that relate to a specific `eventId` (such as thread messages, reactions, etc). So this will probably be useful for you as well. That is done under https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/issues/119

I'm going to close this as a duplicate of #117

**Closed by skylord123** 2024-10-16 20:01 UTC
